AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MeterosStatus
Resources: 
  MeterosStatus:
    Type: AWS::Serverless::Function
    Properties:
      Handler: MeteorsStatus.lambda_handler
      CodeUri: lambda
      Runtime: python3.10
      MemorySize: 256
      Timeout: 60
      ReservedConcurrentExecutions: 1
      Policies:
        - S3ReadPolicy:
            BucketName: meterosdata
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket:
              Ref: meterosdata 
            Events: s3:PutObject
  