name: Deploy MeterosStatus
run-name: ${{ github.actor }} deploying meteros status
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Deploy code"
        run: |
          aws s3api create-bucket --bucket meteors-monitoring-deploy --create-bucket-configuration LocationConstraint=us-west-2 || true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-west-2"
